---
- name: First Play
  hosts: routers
  gather_facts: False
  connection: local
  
  tasks:
  
    - name: First Task
      ios_command:
        commands: sh ip int br | exc un
        
    - name: Second Task
      ios_command:
        commands: sh run int gigabitethernet 0/0
        
  

        
